# Generated by Django 5.1.2 on 2024-10-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo_html', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
    ]
