# Generated by Django 5.1.2 on 2024-10-17 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_licao_alter_usuario_data_de_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='licao',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='Usuario', max_length=150, verbose_name='nome'),
        ),
    ]
